GET   http://localhost:3000/elements?offset=10&limit=10
Content-Type: application/json


###

POST http://localhost:5000/registration
Content-Type: application/json

{
"RegDetails":{
    "username":"test",
    "password":"test",
    "email":"test.mishra@gmail.com"
}
}